server:
  port: 8080

spring:

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  thymeleaf:
    cache: false
    check-template: true
    prefix: classpath:templates/
    suffix: .html

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      ##로컬에서 디비연결
      #jdbc-url: jdbc:mysql://localhost:3306/project?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      #username: my_user
      #password: 1111
      #배포시 디비
      jdbc-url: jdbc:mysql://mydb.c72ss0somxra.ap-northeast-2.rds.amazonaws.com:3306/project?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      username: ${MYSQL_ID}
      password: ${MYSQL_PWD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_PWD}
            scope:
              - email
              - profile
          naver:
            client-id: ${NAVER_ID}
            client-secret: ${NAVER_PWD}
            scope:
              - name
              - email
              - nickname
            client-name: Naver
            authorization-grant-type: authorization_code
            #redirect-uri: http://localhost:8080/login/oauth2/code/naver
            #배포용 네이버 리다이레렉트
            #redirect-uri: http://ec2-43-201-82-12.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/naver
            redirect-uri: http://3.36.56.164:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  # mail
  mail:
    host: smtp.gmail.com
    port: 587
    #로컬용
    #username: ${gamil_id}
    #password: ${gmail_pwd}
    # 배포용
    username: ${GMAIL_ID}
    password: ${GMAIL_PWD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          timeout: 50000
          starttls:
            enable: true
  data:
    redis:
      mail:
        host: localhost
        port: 6379

kakao:
  maps:
    api:
      key: b0724bf330998cfd60824078a8ffae4e